server:
  port: 8080
spring:
  datasource:
    url: "jdbc:h2:file:./test.db"
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
      #ddl-auto: create      # by specifying this it will create the mentioned tables/entities, dangerous for prod data
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG